# Generated by Django 4.1 on 2022-10-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sellers_again',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=15)),
                ('password', models.BigIntegerField()),
                ('phn', models.BigIntegerField()),
                ('address', models.TextField(max_length=15)),
            ],
        ),
    ]
