# Generated by Django 4.1 on 2022-10-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sellers_again',
            new_name='sellers',
        ),
    ]
