# Generated by Django 4.1 on 2022-10-21 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_rename_sellers_again_sellers'),
    ]

    operations = [
        migrations.CreateModel(
            name='products_re',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('description', models.TextField(max_length=500)),
                ('image', models.CharField(max_length=100)),
                ('seeler_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyers.sellers')),
            ],
        ),
    ]
