# Generated by Django 4.1 on 2022-10-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_products_re'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products_re',
            new_name='products',
        ),
    ]
