# Generated by Django 4.1 on 2022-10-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='big_form',
            name='approved',
            field=models.CharField(default='not approved', max_length=100),
        ),
    ]
