# Generated by Django 4.1 on 2022-10-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudtest', '0002_big_form_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='big_form',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
