# Generated by Django 4.1.2 on 2022-11-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudtest', '0004_contacts_alter_big_form_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contacts',
        ),
        migrations.AlterField(
            model_name='big_form',
            name='address',
            field=models.TextField(max_length=200),
        ),
    ]
