# Generated by Django 4.1.2 on 2022-11-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudtest', '0005_delete_contacts_alter_big_form_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='big_form',
            name='approved',
        ),
    ]
