# Generated by Django 4.1.2 on 2022-11-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudtest', '0006_remove_big_form_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='big_form',
            name='approved',
            field=models.CharField(default='not approved', max_length=100),
        ),
    ]
