# Generated by Django 4.1.2 on 2022-11-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuox', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('rate', models.BigIntegerField()),
                ('description', models.TextField(max_length=200)),
                ('approved', models.CharField(default='not approved', max_length=100)),
            ],
        ),
    ]
